feat(deployment): pass in resource request limits as values
armory-io/remote-network-agent-helm-chart pull request #20
Opened 2022-06-10 00:21 UTC by mochacat

Dependent on armory-io/remote-network-agent-helm-chart#19

The new values that can be set are `memoryRequest`, `memoryLimit`, `cpuRequest`, `cpuLimit`. They map to `pec.template.spec.containers[0].resources`.

2022-06-10 00:21 UTC, mochacat commented on templates/_helpers.tpl
> +{{- define "armory-remote-network-agent.resource-request-limits" }}
sorry for how ugly this function is

2022-06-10 00:23 UTC, mochacat commented on values.yaml
> +memoryRequest: "1500Mi"
defaults set here, but the helper function will also set these values in case this gets removed by the user

2022-06-15 20:12 UTC, aelath submitted a review, later dismissed
I kicked the tires on this, LGTM 🌮 

- I had compatibility issues trying to install this in my local minikube cluster. Apparently there can be issues when setting the cpu quotas depending on drivers. I opted to try this in the dev cluster EKS instead.
- This change is now enforcing a minimum resource allocation which some environments might not have. I had to override the cpu just to get it to start up in the dev cluster. As annoying as this is, it's kinda the point of this change set. Documentation and error messaging call this out explicitly. 👍

2022-06-21 17:11 UTC, fieldju approved these changes

2022-06-21 17:12 UTC, fieldju commented
> I had compatibility issues trying to install this in my local minikube cluster. Apparently there can be issues when setting the cpu quotas depending on drivers. I opted to try this in the dev cluster EKS instead.

Is this gonna cause issues for people?

2022-06-21 17:21 UTC, fieldju requested changes
Needs to run in minikube

2022-06-22 18:09 UTC, aelath approved these changes
Nice! LGTM! 🌮

2022-06-22 21:05 UTC, fieldju approved these changes

2022-06-22 21:06 UTC, merged